// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLVoaFzLzuPUmtaNLpWwi-sMlgxarZxx4',
    appId: '1:167145494685:web:6d6029b8a33d4f415b9c74',
    messagingSenderId: '167145494685',
    projectId: 'rafahiya-tourism',
    authDomain: 'rafahiya-tourism.firebaseapp.com',
    databaseURL: 'https://rafahiya-tourism-default-rtdb.firebaseio.com',
    storageBucket: 'rafahiya-tourism.firebasestorage.app',
    measurementId: 'G-LN3TD6X920',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOv9CLPjehyKLCoDJ-ZqwVw81hqAKwUA',
    appId: '1:167145494685:android:314492167ed3dae15b9c74',
    messagingSenderId: '167145494685',
    projectId: 'rafahiya-tourism',
    databaseURL: 'https://rafahiya-tourism-default-rtdb.firebaseio.com',
    storageBucket: 'rafahiya-tourism.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdE9AKcNmlNJi1vZ3Y_YQN3-ZRFlZFYr4',
    appId: '1:167145494685:ios:efb66ca726578a585b9c74',
    messagingSenderId: '167145494685',
    projectId: 'rafahiya-tourism',
    databaseURL: 'https://rafahiya-tourism-default-rtdb.firebaseio.com',
    storageBucket: 'rafahiya-tourism.firebasestorage.app',
    androidClientId: '167145494685-3erudubt113smr18cc5t2k49lk2ddtlm.apps.googleusercontent.com',
    iosClientId: '167145494685-do23e7j6oi91a87ru206s583kafbuohk.apps.googleusercontent.com',
    iosBundleId: 'com.meuzzein.rafahiyatourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdE9AKcNmlNJi1vZ3Y_YQN3-ZRFlZFYr4',
    appId: '1:167145494685:ios:83dc0098942795205b9c74',
    messagingSenderId: '167145494685',
    projectId: 'rafahiya-tourism',
    databaseURL: 'https://rafahiya-tourism-default-rtdb.firebaseio.com',
    storageBucket: 'rafahiya-tourism.firebasestorage.app',
    androidClientId: '167145494685-3erudubt113smr18cc5t2k49lk2ddtlm.apps.googleusercontent.com',
    iosClientId: '167145494685-723kkq1osof01l4gitbvtt5l1gns6k4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.rafahiyatourism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLVoaFzLzuPUmtaNLpWwi-sMlgxarZxx4',
    appId: '1:167145494685:web:f95adf84881252565b9c74',
    messagingSenderId: '167145494685',
    projectId: 'rafahiya-tourism',
    authDomain: 'rafahiya-tourism.firebaseapp.com',
    databaseURL: 'https://rafahiya-tourism-default-rtdb.firebaseio.com',
    storageBucket: 'rafahiya-tourism.firebasestorage.app',
    measurementId: 'G-0RCPMRC8VL',
  );

}