
class CitiesData {
  static final Map<String, List<String>> countryCities = {
    'Saudi Arabia': [
      'Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Al Khobar', 'Dhahran',
      'Taif', 'Tabuk', 'Abha', 'Jizan', 'Al Hofuf', 'Al Qatif', 'Yanbu',
      'Najran', 'Hail', 'Al Bahah', 'Arar', 'Sakakah', 'Al Jubail', 'Al Kharj',
      'Qatif', 'Dhurma', 'Unaizah', 'Rabiq', 'Al Majmaah', 'Al Quwayiyah',
      'Al Mubarraz', 'Al Bukayriyah', 'Al Qunfudhah', 'Al Namas', 'Al Ula',
      'Al Wajh', 'Duba', 'Haql', 'Farasan', 'Sabya', 'Samtah', 'Abu Arish',
      'Al Edabi', 'Al Mithnab', 'Az Zulfi', 'Badr', 'Bisha', 'Dawadmi',
      'Diriyah', 'Haradh', 'Hotat Bani Tamim', 'Layla', 'Al Aflaj',
      'Al Bahah', 'Baljurashi', 'Al Mandaq', 'Qilwah', 'Al Khafji',
      'Al Nairyah', 'Al Qarah', 'Al Qaryat', 'Al Sulayyil', 'Turaif',
      'Umm Lajj', 'Al Badai', 'Al Jafr', 'Al Jandriyah', 'Al Khutwah',
      'Al Markaz', 'Al Muzahimiyah', 'Al Nakhil', 'Al Qasab', 'Al Qurayn',
      'Al Rayn', 'Ar Rass', 'As Sulayyil', 'Ath Thamamah', 'Baqaa',
      'Hautat Sudair', 'Huraymila', 'Rumah', 'Shaqra', 'Thadiq',
      'Ushayqir', 'Wadi Al Dawasir'
    ],

    'India': [
      'Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai',
      'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur',
      'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Pimpri-Chinchwad',
      'Patna', 'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik',
      'Faridabad', 'Meerut', 'Rajkot', 'Kalyan-Dombivli', 'Vasai-Virar',
      'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar', 'Navi Mumbai',
      'Allahabad', 'Howrah', 'Gwalior', 'Jabalpur', 'Coimbatore', 'Vijayawada',
      'Jodhpur', 'Madurai', 'Raipur', 'Kota', 'Chandigarh', 'Guwahati',
      'Solapur', 'Hubli–Dharwad', 'Mysore', 'Tiruchirappalli', 'Bareilly',
      'Aligarh', 'Bhiwandi', 'Gorakhpur', 'Noida', 'Jammu', 'Mangalore',
      'Bhilai', 'Amravati', 'Cuttack', 'Kollam', 'Udaipur', 'Kozhikode',
      'Akola', 'Kurnool', 'Rajahmundry', 'Bokaro', 'South Dumdum', 'Bellary',
      'Patiala', 'Gopalpur', 'Agartala', 'Bhagalpur', 'Muzaffarnagar', 'Bhatpara',
      'Panihati', 'Latur', 'Dhule', 'Tirunelveli', 'Rohtak', 'Korba', 'Bhilwara',
      'Berhampur', 'Muzaffarpur', 'Ahmednagar', 'Mathura', 'Kollam', 'Avadi',
      'Kadapa', 'Kamarhati', 'Sambalpur', 'Bilaspur', 'Shahjahanpur', 'Satara',
      'Bijapur', 'Rampur', 'Shimoga', 'Chandrapur', 'Junagadh', 'Thrissur',
      'Alwar', 'Bardhaman', 'Kulti', 'Nizamabad', 'Parbhani', 'Tumkur',
      'Khammam', 'Uzhavoor', 'Ozhukarai', 'Bihar Sharif', 'Panipat', 'Darbhanga',
      'Bally', 'Aizawl', 'Dewas', 'Ichalkaranji', 'Tirupati', 'Karnal',
      'Bathinda', 'Jalna', 'Barasat', 'Kirari Suleman Nagar', 'Purnia',
      'Satna', 'Mau', 'Sonipat', 'Farrukhabad', 'Sagar', 'Rourkela', 'Durg',
      'Imphal', 'Ratlam', 'Hapur', 'Arrah', 'Karimnagar', 'Anantapur',
      'Etawah', 'Ambernath', 'North Dumdum', 'Bharatpur', 'Begusarai',
      'New Delhi', 'Gandhinagar', 'Baranagar', 'Tiruvottiyur', 'Puducherry',
      'Sikar', 'Thoothukudi', 'Rewa', 'Mirzapur', 'Raichur', 'Pali', 'Ramagundam',
      'Silchar', 'Haridwar', 'Vijayanagaram', 'Tenali', 'Nagercoil', 'Sri Ganganagar',
      'Karawal Nagar', 'Mango', 'Thanjavur', 'Bulandshahr', 'Uluberia',
      'Katni', 'Sambhal', 'Singrauli', 'Nadiad', 'Secunderabad', 'Naihati',
      'Yamunanagar', 'Bidhannagar', 'Pallavaram', 'Bidar', 'Munger', 'Panchkula',
      'Burhanpur', 'Raurkela Industrial Township', 'Kharagpur', 'Dindigul',
      'Gandhidham', 'Hospet', 'Nangloi Jat', 'Malda', 'Ongole', 'Deoghar',
      'Chapra', 'Haldia', 'Khandwa', 'Nandyal', 'Morena', 'Amroha', 'Anand',
      'Bhind', 'Bhalswa Jahangir Pur', 'Madhyamgram', 'Bhiwani', 'Navsari',
      'Ambala', 'Morvi', 'Fatehpur', 'Raebareli', 'Khora', 'Chittoor', 'Bhusawal',
      'Orai', 'Bahraich', 'Phusro', 'Vellore', 'Mehsana', 'Raiganj', 'Sirsa',
      'Danapur', 'Serampore', 'Sultan Pur Majra', 'Guna', 'Jaunpur', 'Panvel',
      'Shivpuri', 'Surendranagar Dudhrej', 'Unnao', 'Chinsurah', 'Alappuzha',
      'Kottayam', 'Machilipatnam', 'Shimla', 'Bhimavaram', 'Karnal', 'Itanagar',
      'Bikaner', 'Dibrugarh', 'Cuddalore', 'Kharagpur', 'Kohima', 'Port Blair',
      'Leh', 'Itanagar', 'Aizawl', 'Shillong', 'Agartala', 'Kohima', 'Gangtok',
      'Kavaratti', 'Daman', 'Silvassa', 'Pondicherry', 'Karaikal', 'Mahe', 'Yanam'
    ],

    'Germany': [
      'Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart',
      'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig', 'Bremen', 'Dresden',
      'Hanover', 'Nuremberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld',
      'Bonn', 'Münster', 'Karlsruhe', 'Mannheim', 'Augsburg', 'Wiesbaden',
      'Gelsenkirchen', 'Mönchengladbach', 'Braunschweig', 'Chemnitz',
      'Kiel', 'Aachen', 'Halle', 'Magdeburg', 'Freiburg', 'Krefeld',
      'Lübeck', 'Oberhausen', 'Erfurt', 'Mainz', 'Rostock', 'Kassel',
      'Hagen', 'Hamm', 'Saarbrücken', 'Mülheim', 'Herne', 'Ludwigshafen',
      'Osnabrück', 'Solingen', 'Leverkusen', 'Oldenburg', 'Neuss', 'Potsdam',
      'Heidelberg', 'Paderborn', 'Darmstadt', 'Würzburg', 'Regensburg',
      'Ingolstadt', 'Heilbronn', 'Ulm', 'Wolfsburg', 'Göttingen', 'Reutlingen',
      'Bremerhaven', 'Fürth', 'Remscheid', 'Koblenz', 'Bergisch Gladbach',
      'Jena', 'Rheda-Wiedenbrück', 'Erlangen', 'Moers', 'Siegen', 'Hildesheim',
      'Salzgitter', 'Cottbus', 'Gütersloh', 'Kaiserslautern', 'Schwerin',
      'Düren', 'Esslingen', 'Ratingen', 'Tübingen', 'Lünen', 'Villingen-Schwenningen',
      'Flensburg', 'Marl', 'Lüneburg', 'Hanau', 'Velbert', 'Minden', 'Dessau-Roßlau',
      'Worms', 'Neumünster', 'Konstanz', 'Norderstedt', 'Delmenhorst', 'Bamberg',
      'Viersen', 'Marburg', 'Rheine', 'Wilhelmshaven', 'Gladbeck', 'Lüdenscheid',
      'Brandenburg an der Havel', 'Bayreuth', 'Celle', 'Stolberg', 'Aschaffenburg',
      'Bocholt', 'Fulda', 'Kempten', 'Landshut', 'Sindelfingen', 'Rosenheim',
      'Frankfurt (Oder)', 'Schwäbisch Gmünd', 'Garbsen', 'Friedrichshafen',
      'Herten', 'Wesel', 'Offenburg', 'Stralsund', 'Grevenbroich', 'Bergheim',
      'Hürth', 'Unna', 'Euskirchen', 'Bad Homburg', 'Langenhagen', 'Langenfeld',
      'Willich', 'Emden', 'Stade', 'Sankt Augustin', 'Hameln', 'Göppingen',
      'Eschweiler', 'Görlitz', 'Meerbusch', 'Pulheim', 'Waiblingen', 'Baden-Baden',
      'Dormagen', 'Neuwied', 'Menden', 'Bad Salzuflen', 'Wetzlar', 'Kleve',
      'Ahlen', 'Wolfenbüttel', 'Frechen', 'Ibbenbüren', 'Schwerte', 'Goslar',
      'Speyer', 'Erftstadt', 'Ravensburg', 'Bad Oeynhausen', 'Peine', 'Elmshorn',
      'Lörrach', 'Frankenthal', 'Bergkamen', 'Rastatt', 'Heidenheim', 'Neustadt',
      'Hennef', 'Soest', 'Leonberg', 'Gronau', 'Alsdorf', 'Homburg', 'Stendal',
      'Freising', 'Cuxhaven', 'Lage', 'Lehrte', 'Oberursel', 'Schwabach',
      'Nordhorn', 'Eisenach', 'Bühl', 'Germering', 'Achim', 'Bitterfeld-Wolfen',
      'Weimar', 'Königswinter', 'Nettetal', 'Bautzen', 'Hof', 'Freiburg im Breisgau',
      'Weiden', 'Neu-Ulm', 'Lohmar', 'Amberg', 'Maintal', 'Kerpen', 'Würselen',
      'Landau', 'Bad Kreuznach', 'Rodgau', 'Oranienburg', 'Falkensee', 'Gaggenau'
    ],
    'United States': [
      'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia',
      'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville',
      'Fort Worth', 'Columbus', 'Charlotte', 'San Francisco', 'Indianapolis',
      'Seattle', 'Denver', 'Washington', 'Boston', 'El Paso', 'Nashville',
      'Detroit', 'Oklahoma City', 'Portland', 'Las Vegas', 'Memphis', 'Louisville',
      'Baltimore', 'Milwaukee', 'Albuquerque', 'Tucson', 'Fresno', 'Sacramento',
      'Mesa', 'Kansas City', 'Atlanta', 'Long Beach', 'Colorado Springs',
      'Raleigh', 'Miami', 'Virginia Beach', 'Omaha', 'Oakland', 'Minneapolis',
      'Tulsa', 'Arlington', 'New Orleans', 'Wichita', 'Cleveland', 'Tampa',
      'Bakersfield', 'Aurora', 'Honolulu', 'Anaheim', 'Santa Ana', 'Corpus Christi',
      'Riverside', 'Lexington', 'St. Louis', 'Stockton', 'Pittsburgh', 'Saint Paul',
      'Cincinnati', 'Anchorage', 'Henderson', 'Greensboro', 'Plano', 'Newark',
      'Lincoln', 'Orlando', 'Irvine', 'Toledo', 'Jersey City', 'Chula Vista',
      'Durham', 'Fort Wayne', 'St. Petersburg', 'Laredo', 'Buffalo', 'Madison',
      'Lubbock', 'Chandler', 'Scottsdale', 'Glendale', 'Reno', 'Norfolk',
      'Winston-Salem', 'North Las Vegas', 'Irving', 'Chesapeake', 'Gilbert',
      'Hialeah', 'Garland', 'Fremont', 'Baton Rouge', 'Richmond', 'Boise',
      'San Bernardino', 'Spokane', 'Des Moines', 'Tacoma', 'Modesto', 'Fontana',
      'Santa Clarita', 'Birmingham', 'Oxnard', 'Fayetteville', 'Moreno Valley',
      'Rochester', 'Glendale', 'Huntington Beach', 'Salt Lake City', 'Grand Rapids',
      'Amarillo', 'Yonkers', 'Aurora', 'Montgomery', 'Columbus', 'Little Rock',
      'Akron', 'Shreveport', 'Augusta', 'Grand Prairie', 'Mobile', 'Huntsville',
      'Tallahassee', 'Overland Park', 'Knoxville', 'Worcester', 'Brownsville',
      'Newport News', 'Santa Barbara', 'Port St. Lucie', 'Providence', 'Fort Lauderdale',
      'Chattanooga', 'Tempe', 'Oceanside', 'Garden Grove', 'Rancho Cucamonga',
      'Cape Coral', 'Santa Rosa', 'Vancouver', 'Sioux Falls', 'Peoria', 'Ontario',
      'Jackson', 'Elk Grove', 'Springfield', 'Pembroke Pines', 'Salem', 'Eugene',
      'Corona', 'McKinney', 'Fort Collins', 'Lancaster', 'Cary', 'Palmdale',
      'Hayward', 'Salinas', 'Frisco', 'Springfield', 'Pasadena', 'Macon', 'Alexandria',
      'Pomona', 'Lakewood', 'Sunnyvale', 'Escondido', 'Kansas City', 'Hollywood',
      'Clarksville', 'Torrance', 'Rockford', 'Joliet', 'Paterson', 'Bridgeport',
      'Naperville', 'Savannah', 'Mesquite', 'Syracuse', 'Orange', 'Fullerton',
      'Killeen', 'Dayton', 'McAllen', 'Bellevue', 'Miramar', 'Hampton', 'West Valley City',
      'Warren', 'Olathe', 'Columbia', 'Thornton', 'Carrollton', 'Midland', 'Charleston',
      'Waco', 'Sterling Heights', 'Denton', 'Cedar Rapids', 'New Haven', 'Roseville',
      'Gainesville', 'Visalia', 'Coral Springs', 'Thousand Oaks', 'Elizabeth',
      'Stamford', 'Concord', 'Surprise', 'Lafayette', 'Topeka', 'Kent', 'Simi Valley',
      'Santa Clara', 'Murfreesboro', 'Hartford', 'Athens', 'Victorville', 'Abilene',
      'Norman', 'Vallejo', 'Berkeley', 'Round Rock', 'Ann Arbor', 'Fargo', 'Columbia',
      'Allentown', 'Evansville', 'Beaumont', 'Odessa', 'Wilmington', 'Arvada',
      'Independence', 'Provo', 'Lansing', 'El Monte', 'Springfield', 'Fairfield',
      'Clearwater', 'Peoria', 'Rochester', 'Carlsbad', 'Westminster', 'West Jordan',
      'Pearland', 'Richardson', 'Downey', 'Miami Gardens', 'Temecula', 'Costa Mesa',
      'College Station', 'Elgin', 'Murrieta', 'Gresham', 'High Point', 'Antioch',
      'Inglewood', 'Cambridge', 'Lowell', 'Manchester', 'Billings', 'Pueblo',
      'Palm Bay', 'Centennial', 'Richmond', 'Ventura', 'Pompano Beach', 'North Charleston',
      'Everett', 'Waterbury', 'West Palm Beach', 'Boulder', 'West Covina', 'Broken Arrow',
      'Clovis', 'Daly City', 'Lakeland', 'Santa Maria', 'Norwalk', 'Sandy Springs',
      'Hillsboro', 'Green Bay', 'Tyler', 'Wichita Falls', 'Lewisville', 'Burbank',
      'Greeley', 'San Mateo', 'El Cajon', 'Jurupa Valley', 'Rialto', 'Davie', 'Tuscaloosa',
      'League City', 'Orem', 'Sparks', 'Waukegan', 'Allen', 'Bellevue', 'Columbia',
      'Miramar', 'Camden', 'Plano', 'Rochester', 'Warren', 'Woodbridge', 'Boca Raton'
    ],

    'United Kingdom': [
      'London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Bristol',
      'Sheffield', 'Leeds', 'Edinburgh', 'Leicester', 'Coventry', 'Bradford',
      'Cardiff', 'Belfast', 'Nottingham', 'Kingston upon Hull', 'Newcastle upon Tyne',
      'Stoke-on-Trent', 'Southampton', 'Derby', 'Portsmouth', 'Brighton', 'Plymouth',
      'Northampton', 'Reading', 'Luton', 'Wolverhampton', 'Bolton', 'Aberdeen',
      'Bournemouth', 'Norwich', 'Middlesbrough', 'Peterborough', 'Swansea',
      'Southend-on-Sea', 'Swindon', 'Dundee', 'Huddersfield', 'York', 'Blackpool',
      'Oxford', 'Ipswich', 'Warrington', 'Slough', 'Crawley', 'Cambridge', 'Doncaster',
      'Gloucester', 'Cheltenham', 'Burnley', 'Watford', 'Gillingham', 'Eastbourne',
      'Milton Keynes', 'Rotherham', 'Newport', 'Barnsley', 'Chester', 'Oldham',
      'St Helens', 'Wigan', 'Basingstoke', 'Southport', 'High Wycombe', 'Exeter',
      'Solihull', 'Worthing', 'Darlington', 'Chelmsford', 'Colchester', 'Saint Albans',
      'Gateshead', 'Stevenage', 'Worcester', 'Bath', 'Lancaster', 'Carlisle',
      'West Bromwich', 'Stockport', 'Wakefield', 'Lincoln', 'Loughborough', 'Hayes',
      'Harrogate', 'Hartlepool', 'Bedford', 'Hemel Hempstead', 'Stevenage', 'Dartford',
      'Wallsend', 'Walsall', 'Maidenhead', 'Wimbledon', 'Rhyl', 'Bebington', 'Acton',
      'Aldershot', 'Ashton-under-Lyne', 'Barnet', 'Basildon', 'Bexleyheath', 'Birkenhead',
      'Blackburn', 'Bletchley', 'Blyth', 'Bognor Regis', 'Bridgend', 'Bridgwater',
      'Bromley', 'Burton upon Trent', 'Bury', 'Camberley', 'Canterbury', 'Chatham',
      'Cheshunt', 'Chesterfield', 'Clacton-on-Sea', 'Corby', 'Cramlington', 'Crawley',
      'Crewe', 'Dagenham', 'Dewsbury', 'Dunfermline', 'Durham', 'East Kilbride',
      'Eastleigh', 'Ellesmere Port', 'Epsom', 'Esher', 'Ewell', 'Fareham', 'Farnborough',
      'Folkestone', 'Gainsborough', 'Gosport', 'Gravesend', 'Grays', 'Guildford',
      'Halesowen', 'Halifax', 'Harlow', 'Harrow', 'Hartlepool', 'Hastings', 'Hatfield',
      'Havant', 'Hazel Grove', 'Heckmondwike', 'Hemel Hempstead', 'Heswall', 'Heywood',
      'Hitchin', 'Hoddesdon', 'Horley', 'Horsham', 'Houghton-le-Spring', 'Hove',
      'Hoylake', 'Hucknall', 'Huyton', 'Hyde', 'Ilford', 'Ilkeston', 'Irvine',
      'Kidderminster', 'Kingswood', 'Kirkby', 'Lancaster', 'Leatherhead', 'Letchworth',
      'Leyland', 'Lichfield', 'Litherland', 'Littlehampton', 'Liversedge', 'Llantrisant'
    ],

    'France': [
      'Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg',
      'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre', 'Saint-Étienne',
      'Toulon', 'Grenoble', 'Dijon', 'Angers', 'Nîmes', 'Villeurbanne', 'Le Mans',
      'Aix-en-Provence', 'Clermont-Ferrand', 'Brest', 'Limoges', 'Tours', 'Amiens',
      'Perpignan', 'Metz', 'Besançon', 'Boulogne-Billancourt', 'Orléans', 'Mulhouse',
      'Rouen', 'Saint-Denis', 'Caen', 'Argenteuil', 'Saint-Paul', 'Montreuil',
      'Nancy', 'Roubaix', 'Tourcoing', 'Nanterre', 'Avignon', 'Vitry-sur-Seine',
      'Créteil', 'Dunkerque', 'Poitiers', 'Asnières-sur-Seine', 'Courbevoie',
      'Versailles', 'Colombes', 'Fort-de-France', 'Aulnay-sous-Bois', 'Saint-Pierre',
      'Rueil-Malmaison', 'Pau', 'Aubervilliers', 'Le Tampon', 'Champigny-sur-Marne',
      'Antibes', 'Béziers', 'La Rochelle', 'Saint-Maur-des-Fossés', 'Cannes', 'Calais',
      'Saint-Nazaire', 'Mérignac', 'Drancy', 'Colmar', 'Ajaccio', 'Bourges', 'Issy-les-Moulineaux',
      'Levallois-Perret', 'La Seyne-sur-Mer', 'Quimper', 'Noisy-le-Grand', 'Villeneuve-dAscq',
      'Neuilly-sur-Seine', 'Valence', 'Antony', 'Cergy', 'Vénissieux', 'Pessac', 'Troyes',
      'Clichy', 'Ivry-sur-Seine', 'Chambéry', 'Lorient', 'Les Abymes', 'Montauban',
      'Sarcelles', 'Niort', 'Villejuif', 'Saint-André', 'Hyères', 'Saint-Quentin',
      'Beauvais', 'Épinay-sur-Seine', 'Cayenne', 'Maisons-Alfort', 'Cholet', 'Meaux',
      'Chelles', 'Pantin', 'Évry', 'Fontenay-sous-Bois', 'Fréjus', 'Vannes', 'Bondy',
      'Le Blanc-Mesnil', 'La Roche-sur-Yon', 'Saint-Louis', 'Arles', 'Clamart',
      'Narbonne', 'Annecy', 'Sartrouville', 'Grasse', 'Laval', 'Belfort', 'Bobigny',
      'Évreux', 'Vincennes', 'Charleville-Mézières', 'Sevran', 'Choisy-le-Roi',
      'Chalon-sur-Saône', 'Albi', 'Mantes-la-Jolie', 'Suresnes', 'Livry-Gargan',
      'Noisy-le-Sec', 'Cagnes-sur-Mer', 'La Courneuve', 'Tarbes', 'Angoulême',
      'Auxerre', 'Boulogne-sur-Mer', 'Le Perreux-Sur-Marne', 'Aubagne', 'Saint-Brieuc',
      'Châlons-en-Champagne', 'Meyzieu', 'Brive-la-Gaillarde', 'Carcassonne', 'Blois',
      'Vaulx-en-Velin', 'Saint-Ouen', 'Alfortville', 'Sète', 'Salon-de-Provence',
      'Garges-lès-Gonesse', 'Bagneux', 'Marcq-en-Barœul', 'Gennevilliers', 'Saint-Priest',
      'Saint-Herblain', 'Istres', 'Valenciennes', 'Châteauroux', 'Thionville', 'Athis-Mons',
      'Compiègne', 'Saint-Germain-en-Laye', 'Saint-Laurent-du-Maroni', 'Talence',
      'Montrouge', 'Castres', 'Douai', 'Arras', 'Bourgoin-Jallieu', 'Wattrelos',
      'Gap', 'Tassin-la-Demi-Lune', 'Bagnolet', 'Le Cannet', 'Saint-Malo', 'Alès',
      'Mâcon', 'Draguignan', 'Anglet', 'Villepinte', 'Pontoise', 'Franconville',
      'Savigny-sur-Orge', 'Conflans-Sainte-Honorine', 'Saint-Raphaël', 'Annemasse',
      'Yerres', 'La Ciotat', 'Roanne', 'Saint-Chamond', 'Chartres', 'Agen', 'Pontault-Combault'
    ],

    'Canada': [
      'Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa',
      'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener', 'London', 'Victoria',
      'Halifax', 'Oshawa', 'Windsor', 'Saskatoon', 'Regina', 'St. Johns',
      'Barrie', 'Kelowna', 'Abbotsford', 'Sherbrooke', 'Guelph', 'Kingston',
      'Kanata', 'Trois-Rivières', 'Moncton', 'Chicoutimi', 'Milton', 'Red Deer',
      'Brantford', 'Thunder Bay', 'Whitehorse', 'Yellowknife', 'Fredericton',
      'Charlottetown', 'Saint John', 'Lethbridge', 'Nanaimo', 'Sudbury', 'Kamloops',
      'Chatham', 'Saint-Jérôme', 'Drummondville', 'Belleville', 'Fort McMurray',
      'Prince George', 'Sarnia', 'Sault Ste. Marie', 'Medicine Hat', 'Grande Prairie',
      'Saint John', 'Penticton', 'Brandon', 'Vernon', 'Courtenay', 'Cornwall',
      'St. Thomas', 'Woodstock', 'Orillia', 'Orangeville', 'Alma', 'Sept-Îles',
      'Val-dOr', 'Shawinigan', 'Rimouski', 'Timmins', 'Sorel-Tracy', 'New Glasgow',
      'Truro', 'Bathurst', 'Miramichi', 'Campbell River', 'Port Alberni', 'Cranbrook',
      'Quesnel', 'Williams Lake', 'Powell River', 'Squamish', 'Whistler', 'Banff',
      'Jasper', 'Canmore', 'Niagara Falls', 'Cambridge', 'Burlington', 'Oakville',
      'Milton', 'Brampton', 'Mississauga', 'Markham', 'Vaughan', 'Richmond Hill',
      'Ajax', 'Pickering', 'Whitby', 'Oshawa', 'Clarington', 'Scugog', 'Uxbridge',
      'Brock', 'Stouffville', 'East Gwillimbury', 'Newmarket', 'Aurora', 'King',
      'Caledon', 'Halton Hills', 'Mono', 'Orangeville', 'Erin', 'Wellington',
      'Guelph-Eramosa', 'Puslinch', 'Centre Wellington', 'Mapleton', 'Minto',
      'Wellington North', 'Southgate', 'West Grey', 'Chatsworth', 'Georgian Bluffs',
      'Meaford', 'The Blue Mountains', 'Grey Highlands', 'South Bruce Peninsula',
      'Northern Bruce Peninsula', 'Kincardine', 'Saugeen Shores', 'Arran-Elderslie',
      'Brockton', 'Huron-Kinloss', 'Ashfield-Colborne-Wawanosh', 'North Huron',
      'Central Huron', 'Morris-Turnberry', 'Howick', 'Huron East', 'Goderich',
      'South Huron', 'Bluewater', 'Lambton Shores', 'Warwick', 'Brooke-Alvinston',
      'Dawn-Euphemia', 'Enniskillen', 'Oil Springs', 'Plympton-Wyoming', 'St. Clair'
    ],
  };
}